### ISSUE TITLE
No log files being returned

### ISSUE THREAD

**Issue by benji1304** [tristenmiller/salesforce-elf-browser#1]
@tristenmiller

Originally logged here, i think this is the correct repo now?
https://github.com/abisek/salesforce-elf-browser/issues/81#issue-1842383446

Basicially, I've not been able to pull any log files for over a month now. Is there an issue with the ELF browser?

**Comment by Mxs2019** [comment]
Same issue here.

**Comment by benji1304** [comment]
Did some digging, I've got not log files generated since June 2023. Is this a salesforce issue?

<img width="438" alt="image" src="https://github.com/tristenmiller/salesforce-elf-browser/assets/7213889/60f2fb57-9ef7-49e4-a5a6-fb9d697ff8ec">

**Comment by tristenmiller** [comment]
I'm guessing that you need to enable 'Generate Event Log Files' in setup https://help.salesforce.com/s/articleView?id=release-notes.rn_security_em_generate_event_log_files.htm&release=244&type=5

**Comment by benji1304** [comment]
That was turned off! Good spot @tristenmiller , thank you. I'll see if new log files are generated later

**Comment by benji1304** [comment]
Thanks @tristenmiller. Sorted.

**Comment by ghost** [comment]
I had the same problem.
Summer'23 disable the log generation

![image](https://github.com/tristenmiller/salesforce-elf-browser/assets/54707551/da19f519-3b6c-4415-a360-ff3bea3c8fe3)

Thanks
